// Import the Recipe model
const Recipe = require('../models/recipe.js');

// Data for the recipes
const recipeData = [
    {   
        recipeName: "Spaghetti Bolognese",
        ingredients: "Spaghetti, Ground Beef, Tomato Sauce, Onion, Garlic, Olive Oil, Salt, Pepper, Parmesan Cheese",
        prepInstructions: "1. Cook the spaghetti according to package instructions. \n 2. In a separate pan, heat the olive oil and cook the chopped onion and garlic until softened. \n 3. Add the ground beef to the pan and cook until browned. \n 4. Stir in the tomato sauce and season with salt and pepper. \n 5. Serve the cooked spaghetti with the Bolognese sauce and sprinkle with grated Parmesan cheese.",
        totalPrepTime: 20,
        cookInstructions: "1. Cook the spaghetti according to package instructions. \n 2. In a separate pan, heat the olive oil and cook the chopped onion and garlic until softened. \n 3. Add the ground beef to the pan and cook until browned. \n 4. Stir in the tomato sauce and season with salt and pepper. \n 5. Serve the cooked spaghetti with the Bolognese sauce and sprinkle with grated Parmesan cheese.",
        totalCookTime: 30,
        picture: './images/001.jpg',
    },
    {
        recipeName: "Fried Rice",
        ingredients: "Rice, Eggs, Carrots, Peas, Corn, Soy Sauce, Sesame Oil, Garlic, Green Onions",
        prepInstructions: "1. Cook the rice according to package instructions. \n 2. In a separate pan, scramble the eggs and set aside. \n 3. In the same pan, stir-fry the chopped vegetables until tender. \n 4. Add the cooked rice to the pan and stir to combine. \n 5. Season with soy sauce and sesame oil. \n 6. Stir in the scrambled eggs and chopped garlic. \n 7. Serve the fried rice garnished with chopped green onions.",
        totalPrepTime: 15,
        cookInstructions: "1. Cook the rice according to package instructions. \n 2. In a separate pan, scramble the eggs and set aside. \n 3. In the same pan, stir-fry the chopped vegetables until tender. \n 4. Add the cooked rice to the pan and stir to combine. \n 5. Season with soy sauce and sesame oil. \n 6. Stir in the scrambled eggs and chopped garlic. \n 7. Serve the fried rice garnished with chopped green onions.",
        totalCookTime: 20,
        picture: './images/002.jpg',
    },
    {
        recipeName: "Classic Spaghetti",
        ingredients: "spaghetti, tomato sauce, ground beef, garlic, olive oil, salt, pepper, parmesan cheese",
        prepInstructions: "1. Bring a large pot of salted water to a boil. \n 2. Cook spaghetti according to package instructions. \n 3. While the spaghetti is cooking, heat the olive oil in a large saucepan over medium heat. \n 4. Add the garlic and cook until fragrant. \n 5. Add the ground beef to the saucepan and cook until browned. \n 6. Pour in the tomato sauce and stir to combine. \n 7. Season with salt and pepper to taste.",
        totalPrepTime: 20,
        cookInstructions: "1. Drain the cooked spaghetti and return it to the pot. \n 2. Pour the sauce over the spaghetti and stir to combine. \n 3. Serve with grated parmesan cheese on top.",
        totalCookTime: 20,
        picture: './images/003.jpg',
    },
    {
        recipeName: "Chicken Stir-Fry",
        ingredients: "chicken breast, bell peppers, onions, carrots, soy sauce, cornstarch, ginger, garlic, oil",
        prepInstructions: "1. Cut the chicken into bite-sized pieces. \n 2. Cut the vegetables into bite-sized pieces. \n 3. In a small bowl, whisk together the soy sauce and cornstarch. \n 4. In a separate bowl, mix together the minced ginger and minced garlic.",
        totalPrepTime: 15,
        cookInstructions: "1. Heat the oil in a large wok over high heat. \n 2. Add the chicken to the wok and cook until browned. \n 3. Add the vegetables to the wok and stir-fry until tender. \n 4. Pour in the soy sauce mixture and stir to combine. \n 5. Serve over steamed rice.",
        totalCookTime: 15,
        picture: './images/004.jpg',
    },
    {
        recipeName: "Lemon Chicken",
        ingredients: "Chicken breasts, Lemon, Garlic, Thyme, Salt, Pepper, Olive oil",
        prepInstructions: "1. Preheat oven to 400°F (200°C). Line a baking dish with parchment paper. \n 2. Season chicken breasts with salt and pepper. \n 3. In a large bowl, whisk together olive oil, lemon juice, minced garlic, and dried thyme. \n 4. Place chicken breasts in the prepared baking dish and pour the lemon mixture over the chicken. \n 5. Bake in preheated oven for 25-30 minutes, or until the internal temperature of the chicken reaches 165°F (74°C). ",
        totalPrepTime: 10,
        cookInstructions: "1. Preheat oven to 400°F (200°C). Line a baking dish with parchment paper. \n 2. Season chicken breasts with salt and pepper. \n 3. In a large bowl, whisk together olive oil, lemon juice, minced garlic, and dried thyme. \n 4. Place chicken breasts in the prepared baking dish and pour the lemon mixture over the chicken. \n 5. Bake in preheated oven for 25-30 minutes, or until the internal temperature of the chicken reaches 165°F (74°C). \n 6. Serve hot with a side of your choice.",
        totalCookTime: 35,
        picture: './images/005.jpg',
    },
    {
        recipeName: "Chicken Alfredo",
        ingredients: "chicken, heavy cream, garlic, grated Parmesan cheese, fettuccine noodles, salt, black pepper, olive oil",
        prepInstructions: "1. Cut chicken into bite-sized pieces and season with salt and black pepper.\n 2. In a large skillet, heat olive oil over medium-high heat. Add chicken and cook until browned on both sides, about 5 minutes.\n 3. Add minced garlic to the skillet and cook for 1 minute.\n 4. Pour in heavy cream and bring to a simmer.\n 5. Stir in grated Parmesan cheese until fully melted.\n 6. Cook fettuccine noodles according to package instructions.\n 7. Drain and add noodles to the skillet with the sauce. Toss until fully coated.",
        totalPrepTime: 20,
        cookInstructions: "1. Cook fettuccine noodles according to package instructions.\n 2. In a large skillet, heat olive oil over medium-high heat. Add chicken and cook until browned on both sides, about 5 minutes.\n 3. Add minced garlic to the skillet and cook for 1 minute.\n 4. Pour in heavy cream and bring to a simmer.\n 5. Stir in grated Parmesan cheese until fully melted.\n 6. Drain and add noodles to the skillet with the sauce. Toss until fully coated.\n 7. Serve hot.",
        totalCookTime: 25,
        picture: './images/006.jpg',
    },
    {
        recipeName: "Strawberry Shortcake",
        ingredients: "strawberries, sugar, all-purpose flour, baking powder, salt, unsalted butter, heavy cream, powdered sugar",
        prepInstructions: "1. Wash and hull strawberries. Slice and add to a bowl.\n 2. Sprinkle sugar over the strawberries and stir to combine. Set aside.\n 3. In a separate bowl, whisk together flour, baking powder, and salt.\n 4. Cut in butter until the mixture resembles coarse crumbs.\n 5. Add heavy cream and stir until just combined.\n 6. Turn dough out onto a floured surface and knead briefly.\n 7. Roll or pat dough out to 1/2-inch thickness. Cut into rounds with a cookie cutter.\n 8. Place rounds on a baking sheet lined with parchment paper.",
        totalPrepTime: 30,
        cookInstructions: "1. Preheat oven to 400°F (200°C).\n 2. Bake for 12-15 minutes, or until golden brown.\n 3. Meanwhile, beat heavy cream and powdered sugar together in a bowl until soft peaks form.\n 4. To serve, split shortcake rounds in half.\n 5. Spoon strawberries and their juices over the bottom half of each round.\n 6. Replace tops and add a dollop of whipped cream.\n 7. Serve immediately.",
        totalCookTime: 15,
        picture: './images/007.jpg',
    },
    {
        recipeName: "Pan-Seared Tilapia",
        ingredients: "Tilapia fillets, lemon juice, garlic, salt, black pepper, olive oil",
        prepInstructions: "1. Rinse the tilapia fillets and pat them dry.\n 2. Squeeze lemon juice over the fillets.\n 3. Crush the garlic and sprinkle it over the fillets.\n 4. Season with salt and black pepper to taste.\n 5. In a pan, heat the olive oil over medium-high heat.\n 6. Place the fillets in the pan and cook for 4-5 minutes on each side or until golden brown.",
        totalPrepTime: 10,
        cookInstructions: "1. In a pan, heat the olive oil over medium-high heat.\n 2. Place the fillets in the pan and cook for 4-5 minutes on each side or until golden brown.",
        totalCookTime: 10,
        picture: './images/008.jpg',
    },
    {
        recipeName: "Zesty Tomato Soup",
        ingredients: "Tomatoes, onion, garlic, vegetable broth, basil, salt, black pepper, heavy cream",
        prepInstructions: "1. Dice the tomatoes and onion.\n 2. Crush the garlic.\n 3. In a pot, heat the vegetable broth over medium heat.\n 4. Add the diced tomatoes, onion, and garlic to the pot.\n 5. Stir in the basil.\n 6. Season with salt and black pepper to taste.\n 7. Let the soup simmer for 20 minutes.",
        totalPrepTime: 20,
        cookInstructions: "1. In a pot, heat the vegetable broth over medium heat.\n 2. Add the diced tomatoes, onion, and garlic to the pot.\n 3. Stir in the basil.\n 4. Season with salt and black pepper to taste.\n 5. Let the soup simmer for 20 minutes.",
        totalCookTime: 20,
        picture: './images/009.jpg',
    },
    {
        recipeName: "Lemon & Herb Roasted Pork Loin",
        ingredients: "Pork Loin, Lemon, Fresh Rosemary, Fresh Thyme, Salt, Black Pepper, Olive Oil",
        prepInstructions: "1. Preheat oven to 400°F. \n 2. Combine lemon juice, salt, black pepper, minced rosemary, thyme in a bowl. \n 3. Rub the pork loin with olive oil and the lemon herb mixture. \n 4. Place in a roasting pan and bake for 30 minutes.",
        totalPrepTime: 15,
        cookInstructions: "1. Reduce oven temperature to 375°F. \n 2. Roast pork loin for an additional 20-25 minutes, until internal temperature reaches 145°F. \n 3. Remove from oven, let rest for 10 minutes before slicing. \n 4. Serve with your favorite sides.",
        totalCookTime: 45,
        picture: './images/010.jpg',
    },        
    {
        recipeName: "Pesto Pasta Salad",
        ingredients: "Penne Pasta, Pesto, Cherry Tomatoes, Kalamata Olives, Red Onion, Feta Cheese",
        prepInstructions: "1. Cook penne pasta according to package instructions. \n 2. Drain and rinse with cold water to cool down. \n 3. In a large bowl, combine the cooked pasta, cherry tomatoes, kalamata olives, diced red onion, and crumbled feta cheese. \n 4. Add pesto and stir until evenly coated.",
        totalPrepTime: 20,
        cookInstructions: "1. Refrigerate pasta salad for at least 30 minutes. \n 2. Serve cold and enjoy!",
        totalCookTime: 0,
        picture: './images/011.jpg',
    },
    {
        recipeName: "Baked Mac and Cheese",
        ingredients: "Elbow macaroni, butter, flour, milk, cheddar cheese, salt, black pepper, breadcrumbs",
        prepInstructions: "1. Cook macaroni according to package instructions. Drain and set aside. \n 2. In a saucepan, melt butter over medium heat. Stir in flour to form a paste. \n 3. Gradually add milk, stirring constantly, until mixture thickens. \n 4. Stir in cheddar cheese until melted and well combined. \n 5. Season with salt and pepper to taste. \n 6. In a greased baking dish, combine cooked macaroni and cheese sauce. \n 7. Sprinkle breadcrumbs on top. \n 8. Bake at 350°F for 25 minutes or until golden brown.",
        totalPrepTime: 20,
        cookInstructions: "1. Preheat oven to 350°F. \n 2. Bake for 25 minutes or until golden brown.",
        totalCookTime: 25,
        picture: './images/012.jpg',
    },
    {
        recipeName: "Chili Con Carne",
        ingredients: "Ground beef, onions, garlic, canned diced tomatoes, chili powder, cumin, paprika, red kidney beans, salt, black pepper, cheddar cheese",
        prepInstructions: "1. In a large pot, brown ground beef over medium heat until fully cooked. Drain excess grease. \n 2. Add onions and garlic to pot and cook until softened. \n 3. Stir in diced tomatoes, chili powder, cumin, and paprika. \n 4. Stir in red kidney beans and season with salt and pepper to taste. \n 5. Reduce heat and let simmer for 30 minutes.",
        totalPrepTime: 20,
        cookInstructions: "1. In a large pot, brown ground beef over medium heat until fully cooked. \n 2. Add onions and garlic and cook until softened. \n 3. Stir in diced tomatoes, chili powder, cumin, and paprika. \n 4. Stir in red kidney beans and season with salt and pepper. \n 5. Reduce heat and let simmer for 30 minutes.",
        totalCookTime: 45,
        picture: './images/013.jpg',
    },
    {
        recipeName: "Grilled Eggplant and Zucchini Salad",
        ingredients: "eggplant, zucchini, cherry tomatoes, balsamic vinegar, olive oil, salt, black pepper, basil leaves",
        prepInstructions: "1. Slice eggplant and zucchini into rounds. \n 2. Halve cherry tomatoes. \n 3. In a small bowl, whisk together balsamic vinegar, olive oil, salt, and pepper. \n 4. Arrange eggplant, zucchini, and cherry tomatoes on a platter. \n 5. Drizzle balsamic mixture over the top. \n 6. Garnish with basil leaves.",
        totalPrepTime: 20,
        cookInstructions: "1. Heat a grill to high heat. \n 2. Lightly oil the grill grates. \n 3. Place eggplant and zucchini rounds on the grill and cook until grill marks appear, about 2-3 minutes per side. \n 4. Remove from grill and place on the platter with cherry tomatoes. \n 5. Serve immediately.",
        totalCookTime: 10,
        picture: './images/014.jpg',
    },
    {
        recipeName: "Crispy Baked Tofu",
        ingredients: "firm tofu, cornstarch, salt, black pepper, garlic powder, onion powder, paprika, olive oil",
        prepInstructions: "1. Drain and press tofu to remove excess water. \n 2. Cut tofu into 1-inch cubes. \n 3. In a shallow dish, mix together cornstarch, salt, pepper, garlic powder, onion powder, and paprika. \n 4. Toss tofu cubes in the cornstarch mixture until coated. \n 5. Place on a wire rack set over a baking sheet.",
        totalPrepTime: 15,
        cookInstructions: "1. Preheat oven to 400°F. \n 2. Drizzle tofu cubes with olive oil. \n 3. Bake for 25-30 minutes, flipping once, until crispy and golden brown. \n 4. Serve immediately.",
        totalCookTime: 30,
        picture: './images/015.jpg',
    },
    {
        recipeName: "Moroccan Spiced Chicken Tagine",
        ingredients: "chicken, onion, garlic, olive oil, ginger, ground cumin, ground coriander, salt, black pepper, dried apricots, raisins, coriander leaves, lemons, almonds",
        prepInstructions: "1. Rinse chicken and cut into serving pieces. \n 2. Chop onion and crush garlic. \n 3. Grate ginger. \n 4. In a bowl, mix together cumin, coriander, salt, and black pepper. \n 5. Roughly chop apricots and raisins. \n 6. Pick coriander leaves and slice lemons.",
        totalPrepTime: 20,
        cookInstructions: "1. In a large pan, heat olive oil over medium heat. \n 2. Add chicken and cook until browned. \n 3. Remove chicken from pan. \n 4. In the same pan, add onion, garlic, and ginger. Cook until onion is soft. \n 5. Add spices and cook for 1 minute. \n 6. Add chicken back to the pan. \n 7. Add apricots, raisins, coriander leaves, and sliced lemons. \n 8. Cover and simmer for 30 minutes or until chicken is cooked through. \n 9. Toast almonds in a separate pan and sprinkle on top of the tagine before serving.",
        totalCookTime: 50,
        picture: './images/016.jpg',
    },
    {
        recipeName: "Spicy Grilled Shrimp Skewers",
        ingredients: "shrimp, red pepper, yellow pepper, red onion, olive oil, cumin, coriander, chili powder, garlic, lemon juice, salt, black pepper",
        prepInstructions: "1. Peel and devein shrimp. \n 2. Cut red and yellow pepper into bite-sized pieces. \n 3. Cut onion into wedges. \n 4. In a bowl, mix together olive oil, cumin, coriander, chili powder, minced garlic, lemon juice, salt, and black pepper.",
        totalPrepTime: 15,
        cookInstructions: "1. Preheat grill to medium heat. \n 2. Thread shrimp, peppers, and onion onto skewers. \n 3. Brush skewers with the oil and spice mixture. \n 4. Grill for 4-5 minutes on each side or until shrimp are pink and cooked through. \n 5. Serve with extra lemon wedges.",
        totalCookTime: 20,
        picture: './images/017.jpg',
    },   
    {
        recipeName: "Thai Green Curry Chicken",
        ingredients: "chicken breast, green curry paste, coconut milk, fish sauce, brown sugar, lime juice, basil, bell peppers, onions, carrots",
        prepInstructions: "1. Cut chicken breast into 1 inch pieces. \n 2. Cut bell peppers, onions, and carrots into bite-sized pieces. \n 3. In a small bowl, whisk together the green curry paste, coconut milk, fish sauce, brown sugar, and lime juice. \n 4. In a separate pan, heat oil and add chicken. Cook until browned. \n 5. Add bell peppers, onions, and carrots to pan. Cook for 3 minutes. \n 6. Pour the green curry sauce over the chicken and vegetables. \n 7. Simmer for 10-15 minutes. \n 8. Serve with rice and garnish with basil.",
        totalPrepTime: 30,
        cookInstructions: "1. Heat oil in a pan. \n 2. Add chicken and cook until browned. \n 3. Add bell peppers, onions, and carrots to pan. Cook for 3 minutes. \n 4. Pour the green curry sauce over the chicken and vegetables. \n 5. Simmer for 10-15 minutes. \n 6. Serve with rice and garnish with basil.",
        totalCookTime: 20,
        picture: './images/018.jpg',
    },
    {
        recipeName: "Quinoa Stuffed Bell Peppers",
        ingredients: "bell peppers, quinoa, vegetable broth, olive oil, onions, garlic, diced tomatoes, black beans, corn, cheddar cheese, salt, pepper",
        prepInstructions: "1. Preheat oven to 375°F. \n 2. Cut the top off of the bell peppers and remove the seeds. \n 3. In a pan, cook the quinoa in vegetable broth. \n 4. In a separate pan, heat olive oil and add onions and garlic. Cook until softened. \n 5. Add diced tomatoes, black beans, and corn to the pan. \n 6. Mix in the cooked quinoa and season with salt and pepper. \n 7. Stuff the mixture into the bell peppers. \n 8. Top each pepper with cheddar cheese. \n 9. Bake for 25-30 minutes.",
        totalPrepTime: 30,
        cookInstructions: "1. Preheat oven to 375°F. \n 2. Bake stuffed bell peppers for 25-30 minutes.",
        totalCookTime: 30,
        picture: './images/019.jpg',
    },   
    {
        recipeName: "Crab Cakes with Lemon Aioli",
        ingredients: "crab meat, breadcrumbs, mayonnaise, lemon juice, dijon mustard, old bay seasoning, parsley, egg, vegetable oil",
        prepInstructions: "1. In a large bowl, mix together crab meat, breadcrumbs, mayonnaise, lemon juice, dijon mustard, old bay seasoning, parsley, and egg until well combined. \n 2. Form the mixture into 4-6 patties. \n 3. In a large pan, heat the oil over medium heat. \n 4. Cook the crab cakes for 4-5 minutes on each side, until golden brown.",
        totalPrepTime: 10,
        cookInstructions: "1. In a small bowl, mix together mayonnaise, lemon juice, and dijon mustard. \n 2. Serve the crab cakes with the lemon aioli on the side.",
        totalCookTime: 20,
        picture: './images/020.jpg',
    },
    {
        recipeName: "Beef and Broccoli Stir-Fry",
        ingredients: "beef, broccoli, soy sauce, brown sugar, cornstarch, vegetable oil, ginger, garlic",
        prepInstructions: "1. Cut the beef into thin strips. \n 2. In a small bowl, mix together soy sauce, brown sugar, and cornstarch. \n 3. Cut the broccoli into small florets. \n 4. In a large pan, heat the oil over medium heat. \n 5. Add the ginger and garlic and cook for 1 minute. \n 6. Add the beef and cook for 2-3 minutes, until browned. \n 7. Add the broccoli and cook for 3-4 minutes, until tender.",
        totalPrepTime: 10,
        cookInstructions: "1. Stir in the soy sauce mixture. \n 2. Cook for an additional 1-2 minutes, until the sauce has thickened. \n 3. Serve hot over rice.",
        totalCookTime: 15,
        picture: './images/021.jpg',
    },
    {
        recipeName: "Baked Stuffed Shells",
        ingredients: "jumbo pasta shells, ricotta cheese, mozzarella cheese, parmesan cheese, egg, basil, oregano, salt, pepper, marinara sauce",
        prepInstructions: "1. Preheat oven to 375°F. Cook pasta shells according to package instructions until al dente.\n  2. In a large bowl, mix together the ricotta cheese, 1 cup of mozzarella cheese, 1/4 cup of parmesan cheese, egg, chopped basil, oregano, salt, and pepper.\n  3. Spoon about 2 tablespoons of the cheese mixture into each shell.\n  4. Spread 1 cup of marinara sauce in the bottom of a 9x13 inch baking dish. Place the stuffed shells on top of the sauce.\n  5. Sprinkle the remaining mozzarella and parmesan cheese on top of the shells.\n  6. Cover the dish with foil and bake for 25 minutes.\n  7. Remove the foil and bake for an additional 10 minutes, or until the cheese is melted and bubbly.",
        totalPrepTime: 20,
        cookInstructions: "1. Preheat oven to 375°F.\n  2. Bake the stuffed shells, covered with foil, for 25 minutes.\n  3. Remove the foil and bake for an additional 10 minutes, or until the cheese is melted and bubbly.",
        totalCookTime: 35,
        picture: './images/022.jpg',
    },
    {
        recipeName: "Roasted Garlic and Tomato Focaccia",
        ingredients: "focaccia bread, olive oil, garlic, salt, black pepper, cherry tomatoes, basil",
        prepInstructions: "1. Preheat oven to 400°F.\n  2. Cut the focaccia bread in half horizontally. Brush the cut sides of the bread with olive oil.\n  3. In a small bowl, mix together minced garlic, salt, and pepper. Spread the garlic mixture on the cut sides of the bread.\n  4. Place cherry tomatoes on top of the garlic mixture.\n  5. Bake for 15-20 minutes, or until the bread is golden brown and the tomatoes are tender.\n  6. Remove from the oven and sprinkle with chopped basil.",
        totalPrepTime: 10,
        cookInstructions: "1. Preheat oven to 400°F.\n  2. Bake the focaccia for 15-20 minutes, or until the bread is golden brown and the tomatoes are tender.",
        totalCookTime: 20,
        picture: './images/023.jpg',
    },
    {
        recipeName: "Beef and Mushroom Stroganoff",
        ingredients: "beef tenderloin, mushrooms, onion, garlic, flour, beef broth, sour cream, butter, salt, pepper",
        prepInstructions: "1. Slice the beef into thin strips. \n 2. Finely chop the onion and mince the garlic. \n 3. Clean and slice the mushrooms. \n 4. In a small bowl, mix together the flour and some salt and pepper. \n 5. In another bowl, whisk the beef broth and sour cream together. \n 6. In a large pan, melt the butter over medium heat. \n 7. Add the beef strips and cook until browned, about 5 minutes. \n 8. Remove the beef from the pan and set aside. \n 9. In the same pan, add the onion and cook until softened, about 5 minutes. \n 10. Add the garlic and mushrooms and cook until the mushrooms release their liquid, about 5 minutes. \n 11. Sprinkle the flour mixture over the vegetables and stir to combine. \n 12. Gradually add the beef broth mixture, stirring constantly until the sauce thickens, about 5 minutes. \n 13. Return the beef to the pan and stir to combine. \n 14. Serve over egg noodles.",
        totalPrepTime: 30,
        cookInstructions: "1. Cook the egg noodles according to package instructions. \n 2. In a large pan, melt the butter over medium heat. \n 3. Add the beef strips and cook until browned, about 5 minutes. \n 4. Remove the beef from the pan and set aside. \n 5. In the same pan, add the onion and cook until softened, about 5 minutes. \n 6. Add the garlic and mushrooms and cook until the mushrooms release their liquid, about 5 minutes. \n 7. Sprinkle the flour mixture over the vegetables and stir to combine. \n 8. Gradually add the beef broth mixture, stirring constantly until the sauce thickens, about 5 minutes. \n 9. Return the beef to the pan and stir to combine. \n 10. Serve the stroganoff over the cooked egg noodles.",
        totalCookTime: 40,
        picture: './images/024.jpg',
    },
    {
        recipeName: "Sweet Potato & Lentil Stew",
        ingredients: "Sweet potatoes, Lentils, Onions, Garlic, Carrots, Tomatoes, Vegetable broth, Cumin, Coriander, Turmeric",
        prepInstructions: "1. Dice the onions, mince the garlic and peel and dice the carrots. \n 2. Wash and drain the lentils. \n 3. Peel and dice the sweet potatoes. \n 4. Dice the tomatoes.",
        totalPrepTime: 20,
        cookInstructions: "1. In a large pot, heat olive oil over medium heat. Add the onions and cook until softened, about 5 minutes. \n 2. Add the garlic and cook for 1 minute. \n 3. Add the carrots, sweet potatoes, lentils, diced tomatoes, cumin, coriander and turmeric to the pot. Stir to combine. \n 4. Pour in the vegetable broth and bring the stew to a boil. \n 5. Reduce heat to low, cover and let simmer for 25-30 minutes or until the vegetables are tender and the lentils are cooked.",
        totalCookTime: 30,
        picture: './images/025.jpg',
    },
    {
        recipeName: "Pork & Apple Skewers",
        ingredients: "Pork tenderloin, Apples, Red onion, Honey, Balsamic vinegar, Olive oil, Rosemary, Thyme",
        prepInstructions: "1. Cut the pork into 1 inch cubes. \n 2. Cut the apples into 1 inch cubes. \n 3. Cut the red onion into wedges. \n 4. In a small bowl, whisk together the honey, balsamic vinegar, olive oil, rosemary and thyme to make a marinade.",
        totalPrepTime: 15,
        cookInstructions: "1. Place the pork cubes, apple cubes and red onion wedges on skewers, alternating each ingredient. \n 2. Brush the marinade onto the skewers. \n 3. Preheat a grill to medium-high heat. \n 4. Place the skewers onto the grill and cook, turning occasionally, for 10-15 minutes or until the pork is cooked through and the apples are slightly charred.",
        totalCookTime: 15,
        picture: './images/026.jpg',
    },
    {
        recipeName: "Chile Verde Pork Stew",
        ingredients: "pork shoulder, yellow onion, garlic, canned diced green chilies, canned diced tomatoes, chicken broth, jalapeno pepper, cumin, dried oregano, dried cilantro",
        prepInstructions: "1. Cut the pork shoulder into 1-inch cubes. \n 2. Dice the onion and mince the garlic. \n 3. Cut the jalapeno pepper in half, remove the seeds and stem, and mince. \n 4. Measure out the spices. \n 5. Open the cans of green chilies and diced tomatoes.",
        totalPrepTime: 20,
        cookInstructions: "1. In a large pot, heat some oil over medium-high heat. \n 2. Add the pork and cook until browned on all sides. \n 3. Add the onion, garlic, and jalapeno pepper to the pot and cook until the onion is soft. \n 4. Stir in the green chilies, diced tomatoes, chicken broth, cumin, oregano, and cilantro. \n 5. Bring the mixture to a boil, then reduce heat to low and simmer for 2-3 hours or until the pork is tender.",
        totalCookTime: 180,
        picture: './images/027.jpg',
    },
    {
        recipeName: "Creamy Tomato & Spinach Pasta",
        ingredients: "spaghetti, cherry tomatoes, baby spinach leaves, heavy cream, grated parmesan cheese, garlic, red pepper flakes",
        prepInstructions: "1. Cook the spaghetti according to package directions. \n 2. Halve the cherry tomatoes. \n 3. Chop the baby spinach leaves. \n 4. Measure out the heavy cream, grated parmesan cheese, and red pepper flakes. \n 5. Mince the garlic.",
        totalPrepTime: 10,
        cookInstructions: "1. In a large saucepan, heat some oil over medium heat. \n 2. Add the garlic and cook until fragrant. \n 3. Stir in the cherry tomatoes and red pepper flakes and cook for 2-3 minutes or until the tomatoes start to burst. \n 4. Add the heavy cream to the saucepan and bring to a simmer. \n 5. Stir in the grated parmesan cheese until melted and smooth. \n 6. Stir in the baby spinach leaves until wilted. \n 7. Drain the spaghetti and add it to the saucepan. \n 8. Toss the pasta in the sauce to combine.",
        totalCookTime: 20,
        picture: './images/028.jpg',
    },
    {
        recipeName: "Roasted Butternut Squash Soup",
        ingredients: "Butternut squash, Olive oil, Garlic, Onion, Vegetable broth, Thyme, Cinnamon, Nutmeg, Salt, Pepper",
        prepInstructions: "Peel and dice the butternut squash. Mince the garlic and chop the onion. In a large pot, heat the olive oil over medium heat and sauté the garlic and onion until softened.",
        totalPrepTime: 30,
        cookInstructions: "1. Add the diced butternut squash, vegetable broth, thyme, cinnamon, nutmeg, salt, and pepper to the pot. \n 2. Bring to a boil and then reduce heat and simmer for 25-30 minutes. \n 3. Blend the soup until smooth and serve hot.",
        totalCookTime: 35,
        picture: './images/029.jpg',
    },
    {
        recipeName: "Caribbean Jerk Pork Chops",
        ingredients: "Pork chops, Jerk seasoning, Lime juice, Honey, Garlic, Onion, Paprika, Cumin, Allspice",
        prepInstructions: "1. In a large bowl, mix together the jerk seasoning, lime juice, honey, minced garlic and onion. \n 2. Place the pork chops in the mixture and marinate for at least 30 minutes.",
        totalPrepTime: 60,
        cookInstructions: "1. Preheat oven to 400°F. \n 2. In a small bowl, mix together paprika, cumin, and allspice. \n 3. Remove the pork chops from the marinade and coat in the spice mixture. \n 4. Bake for 25-30 minutes, or until the internal temperature of the pork reaches 145°F.",
        totalCookTime: 35,
        picture: './images/030.jpg',
    }
]

// Function to bulk create the recipe records in the database
const seedRecipes = () => Recipe.bulkCreate(recipeData);

// Export the seedRecipes function so it can be imported in other parts of the app
module.exports = seedRecipes;